builds:
  - binary: go-cal
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: go-cal
    homepage: "https://github.com/lkyuchukov/go-cal"
    tap:
      owner: lkyuchukov
      name: homebrew-go-cal

checksum:
  name_template: 'checksums.txt'
